import React from 'react';
import Card,{CardHeader,CardContent,CardFooter} from './Card';
import Badge from './Badge';
import Button from './Button';
interface StatCardProps{label:string;value:string|number;change?:string;icon:string;}
const StatCard:React.FC<StatCardProps>=({label,value,change,icon})=><Card><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-neutral-600">{label}</p><h3 className="text-2xl font-bold text-neutral-900 mt-2">{value}</h3>{change&&<p className="text-xs text-success-600 mt-2">↑ {change}</p>}</div><div className="text-3xl">{icon}</div></div></Card>;
const upcomingProgrammes=[{id:'1',name:'AI Innovation Hackathon',date:'2024-10-15',status:'published',participants:45},{id:'2',name:'Startup Pitching Competition',date:'2024-10-22',status:'published',participants:32},{id:'3',name:'Design Challenge',date:'2024-10-29',status:'draft',participants:0}] as const;
const recentActivities=[{id:'1',action:'registered for',actor:'Faris M',timestamp:'2 hours ago'},{id:'2',action:'submitted results for',actor:'Judge Sarah',timestamp:'4 hours ago'},{id:'3',action:'created new programme',actor:'Admin',timestamp:'1 day ago'}];
const DashboardHome:React.FC=()=> <div className="space-y-6"><div><h1 className="text-3xl font-bold text-neutral-900">Welcome back, Faris</h1><p className="text-neutral-600 mt-1">Here's what's happening with your festival today.</p></div>
<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><StatCard label="Total Participants" value="1,248" change="12% this week" icon="👥"/><StatCard label="Active Programmes" value="8" change="2 new" icon="📋"/><StatCard label="Registrations" value="324" change="8% this week" icon="✏️"/><StatCard label="Results Submitted" value="156" change="92% complete" icon="🏆"/></div>
<div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="lg:col-span-2 space-y-6"><Card><CardHeader title="Upcoming Programmes" subtitle="Your scheduled events"/><CardContent><div className="space-y-3">{upcomingProgrammes.map(p=><div key={p.id} className="flex items-start justify-between p-3 hover:bg-neutral-50 rounded-lg transition-colors"><div className="flex-1"><div className="flex items-center gap-2"><h4 className="font-medium text-neutral-900">{p.name}</h4><Badge variant={p.status as 'published'|'draft'} size="sm">{p.status.charAt(0).toUpperCase()+p.status.slice(1)}</Badge></div><p className="text-sm text-neutral-500 mt-1">📅 {new Date(p.date).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</p></div><div className="text-right"><p className="text-sm font-medium text-primary-600">{p.participants}</p><p className="text-xs text-neutral-500">registered</p></div></div>)}</div></CardContent><CardFooter><Button variant="secondary" size="sm">View All Programmes</Button></CardFooter></Card>
<Card><CardHeader title="Registration Overview" subtitle="Current registration status"/><CardContent><div className="space-y-4">{[{label:'Confirmed',count:324,percentage:85},{label:'Pending',count:45,percentage:12},{label:'Cancelled',count:12,percentage:3}].map(item=><div key={item.label}><div className="flex justify-between mb-1"><span className="text-sm font-medium text-neutral-700">{item.label}</span><span className="text-sm font-semibold text-neutral-900">{item.percentage}%</span></div><div className="w-full bg-neutral-200 rounded-full h-2 overflow-hidden"><div className="bg-primary-500 h-full transition-all duration-300" style={{width:\`\${item.percentage}%\`}}/></div><p className="text-xs text-neutral-500 mt-1">{item.count} registrations</p></div>)}</div></CardContent></Card></div>
<div className="space-y-6"><Card><CardHeader title="Pending Actions"/><CardContent><div className="space-y-3">{[{label:'Review judge submissions',icon:'⭐',count:3},{label:'Generate certificates',icon:'📜',count:1},{label:'Approve announcements',icon:'📢',count:2},{label:'Verify participant data',icon:'✓',count:5}].map((a,i)=><div key={i} className="flex items-start gap-3 p-2 hover:bg-neutral-50 rounded-lg transition-colors"><span className="text-lg mt-0.5">{a.icon}</span><div className="flex-1"><p className="text-sm font-medium text-neutral-700">{a.label}</p><p className="text-xs text-neutral-500 mt-0.5">{a.count} pending</p></div></div>)}</div></CardContent></Card>
<Card><CardHeader title="Recent Activity"/><CardContent><div className="space-y-3">{recentActivities.map(a=><div key={a.id} className="pb-3 border-b border-neutral-200 last:border-0 last:pb-0"><p className="text-sm text-neutral-700"><span className="font-semibold">{a.actor}</span> {a.action}</p><p className="text-xs text-neutral-500 mt-1">{a.timestamp}</p></div>)}</div></CardContent><CardFooter><Button variant="secondary" size="sm">View Activity Log</Button></CardFooter></Card></div></div></div>;
export default DashboardHome;