import React,{useState} from 'react';
import clsx from 'clsx';
interface DashboardLayoutProps{children:React.ReactNode;sidebarOpen?:boolean;onSidebarToggle?:(open:boolean)=>void;}
const DashboardLayout:React.FC<DashboardLayoutProps>=({children,sidebarOpen=true,onSidebarToggle})=>{
const [mobileSidebarOpen,setMobileSidebarOpen]=useState(false);
const toggleSidebar=(open:boolean)=>{setMobileSidebarOpen(open);onSidebarToggle?.(open);};
const navItems=[{label:'Dashboard',icon:'📊',href:'/dashboard'},{label:'Events',icon:'📅',href:'/events'},{label:'Programmes',icon:'📋',href:'/programmes'},{label:'Participants',icon:'👥',href:'/participants'},{label:'Judging',icon:'⭐',href:'/judging'},{label:'Results',icon:'🏆',href:'/results'},{label:'Certificates',icon:'📜',href:'/certificates'},{label:'Announcements',icon:'📢',href:'/announcements'},{label:'Downloads',icon:'💾',href:'/downloads'},{label:'Analytics',icon:'📈',href:'/analytics'}];
return <div className="flex h-screen bg-neutral-50">
<aside className={clsx('fixed inset-y-0 left-0 z-40 w-64 bg-neutral-0 shadow-lg','transition-transform duration-300 ease-in-out','md:relative md:translate-x-0',mobileSidebarOpen?'translate-x-0':'-translate-x-full')}>
<div className="flex items-center justify-between h-16 px-4 border-b border-neutral-200"><h1 className="text-xl font-bold text-primary-600">EVENTRA</h1><button onClick={()=>toggleSidebar(false)} className="md:hidden p-2 hover:bg-neutral-100 rounded-lg transition-colors">✕</button></div>
<nav className="p-4 space-y-1 overflow-y-auto flex-1">{navItems.map(item=><a key={item.href} href={item.href} className={clsx('flex items-center gap-3 px-4 py-2.5 rounded-lg','text-neutral-700 font-medium','transition-all duration-200','hover:bg-neutral-100 hover:text-primary-600','focus-visible:outline-2 focus-visible:outline-primary-500 focus-visible:outline-offset-2')}><span className="text-lg">{item.icon}</span><span>{item.label}</span></a>)}</nav>
<div className="p-4 border-t border-neutral-200 space-y-2"><a href="/settings" className="flex items-center gap-3 px-4 py-2.5 rounded-lg text-neutral-700 hover:bg-neutral-100 transition-colors"><span>⚙️</span><span>Settings</span></a><a href="/profile" className="flex items-center gap-3 px-4 py-2.5 rounded-lg text-neutral-700 hover:bg-neutral-100 transition-colors"><span>👤</span><span>Profile</span></a></div>
</aside>
{mobileSidebarOpen&&<div className="fixed inset-0 z-30 bg-black bg-opacity-50 md:hidden" onClick={()=>toggleSidebar(false)}/>}
<div className="flex-1 flex flex-col overflow-hidden"><header className="h-16 bg-neutral-0 border-b border-neutral-200 px-4 md:px-6 flex items-center justify-between"><button onClick={()=>toggleSidebar(true)} className="md:hidden p-2 hover:bg-neutral-100 rounded-lg transition-colors">☰</button><div className="flex-1"/><div className="flex items-center gap-4"><input type="search" placeholder="Search..." className="hidden md:block px-4 py-2 rounded-lg border border-neutral-200 text-sm focus:outline-none focus:ring-2 focus:ring-primary-500"/><button className="p-2 hover:bg-neutral-100 rounded-lg transition-colors">🔔</button><div className="w-8 h-8 rounded-full bg-gradient-to-br from-primary-400 to-accent-400"/></div></header><main className="flex-1 overflow-y-auto p-4 md:p-6"><div className="max-w-7xl mx-auto">{children}</div></main></div>
</div>};
export default DashboardLayout;